version: '2'
services:
  ssh-honeypot:
    image: 'local/ssh-honeypot:latest'
    restart: unless-stopped
    build: .
    ports:
      - '22:2022'
    volumes:
      - ./ssh-honeypot.log:/home/honeycomb/log
      - rsa:/home/honeycomb/rsa
    networks:
      default:

volumes:
  rsa:
    driver: local

networks:
  default:
